before_install:
  - sudo apt-get -y install libgsl-dev
addons:
  apt:
    update: true

# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov(path = "R/", line_exclusions = list("R/method_plot.R" = c(54, 79), "R/glmdisc.R" = 4:5))'