# This workflow will install R dependencies, run tests and lint with a variety of R versions

name: R package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: r-base:latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up R and install dependencies
      run: |
        apt-get update
        apt-get -y install libxml2-dev
        apt-get -y install libssl-dev
        apt-get -y install libcurl4-openssl-dev
        apt-get -y install libgit2-dev
        apt-get -y install libssh2-1-dev
        apt-get -y install pandoc
        r -e "install.packages('devtools')"
        r -e 'devtools::install_deps()'
