name: R package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies for devtools
        run: |
          sudo apt-get update -y
          sudo apt-get install libgit2-dev -y
          sudo apt-get install libssh2-1-dev -y
      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}
      - name: Build
        run: devtools::build(binary = TRUE)
        shell: Rscript {0}
