# This workflow will install R dependencies, run tests and lint with a variety of R versions

name: R package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        R: [ '3.5.3', '3.6.1', '4.0.2' ]
    name: R ${{ matrix.R }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: r-lib/actions/setup-R@v1
        with:
          r-version: ${{ matrix.R }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up R and install dependencies
      run: |
        apt-get update
        apt-get -y install libxml2-dev
        apt-get -y install libssl-dev
        apt-get -y install libcurl4-openssl-dev
        apt-get -y install libgit2-dev
        apt-get -y install libssh2-1-dev
        apt-get -y install pandoc
        r -e "install.packages('devtools')"
        r -e 'devtools::install_deps()'
