name: R package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        R: [ '3.5.3', '3.6.1', '4.0.2' ]
    name: R ${{ matrix.R }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-R@V1
        with:
          r-version: ${{ matrix.R }}
      - name: Build
        run: |
          r -e 'devtools::build(binary = TRUE)'
