name: R package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        R: [ '3.5.3', '3.6.1', '4.0.2' ]
    name: R ${{ matrix.R }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
          apt update -y
          apt install r-base -y
          r -e 'devtools::build(binary = TRUE)'
